export const ROLES = {
	INVESTOR: 'INVESTOR',
	SECURITY: 'SECURITY',
	MANAGER: 'MANAGER',
}

export const PROJECT_STATUS = {
	CREATED: 'CREATED',
	WAITING_FOR_APPLICANT_APPROVAL: 'WAITING_FOR_APPLICANT_APPROVAL',
	APPLICANT_APPROVED: 'APPLICANT_APPROVED',
	SCORING_RESULT_APPROVED: 'SCORING_RESULT_APPROVED',
}